server:
  servlet:
    context-path: /sell
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.0.51:3306/sellorder?characterEncoding=utf-8
    username: root
    password: 123456
  jpa:
    show-sql: true

